print("Welcome to my first game! The object is to survive all 10 levels. You cannot leave the screen, backtrack, or cross your trail, even if the computer takes over. The controls are W,A,S,and D. Don't give up, you'll get the hang of it! Good Luck!")

import turtle
turtle.left(90)
def bad_guy():
    turtle.forward(100)
    turtle.right(25)
    turtle.forward(50)
    turtle.left(115)
    turtle.forward(43)
    turtle.left(115)
    turtle.forward(50)
    turtle.right(25)
    turtle.forward(100)
    turtle.left(180)
def WASD(W):
    if (W == "w"):
        turtle.forward(50)
    elif (W == "a"):
        turtle.left(90)
    else:
        if (W == "s"):
            turtle.right(180)
            turtle.forward(20)
        elif (W == "d"):
            turtle.right(90)
        else:
            print("invalid move")
        
bad_guy()
print("10 moves")
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
bad_guy()
print("level up! 9 moves")
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
bad_guy()
print("level up! 8 moves")
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
bad_guy()
print("level up! 6 moves")
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
bad_guy()
print("level up! 5 moves")
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
bad_guy()
print("level up! 4 moves")
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
bad_guy()
print("level up! 3 moves")
a = input()
WASD(a)
a = input()
WASD(a)
a = input()
WASD(a)
bad_guy()
print("level up! 2 moves")
a = input()
WASD(a)
a = input()
WASD(a)
print("level up! 1 move")
a = input()
WASD(a)
turtle.forward(500)
print("Congrats! You beat the game!")


